### ISSUE TITLE
Cannot access dev apps when home directory is 700

### ISSUE THREAD

**Issue by ericfranz** [OSC/nginx_stage#12]
I can create and deploy an app, but cannot access it.

For example, as an0047, my home directory was 700. I created a copy of the dashboard at /users/PAN0014/an0047/awesim/dev/dashboard

When I went to https://apps-dev.awesim.org/pun/dev/dashboard I was redirected to https://apps-dev.awesim.org/nginx/init?redir=%2fpun%2fdev%2fdashboard and saw this:

>Error -- invalid app root: /users/PAN0014/an0047/awesim/dev/dashboard
>Run 'nginx_stage --help' to see a full list of available command line options.

**Comment by nickjer** [comment]
May be caused by `root` not having privileged access to the NFS filesystem. Will have to look into switching to the user temporarily for checks, then switching back to `root`.

**Comment by nickjer** [comment]
Problematic code here:

https://github.com/OSC/nginx_stage/blob/5ba5c2c4e1466c29ffe70f445ce35052ebaaf41a/lib/nginx_stage/generators/app_config_generator.rb#L68-L71

**Comment by nickjer** [comment]
May cause problems in other locations:

https://github.com/OSC/nginx_stage/blob/69f735cf118b43907f7f39cbb264b68cad603324/lib/nginx_stage/generators/app_clean_generator.rb#L26
